runtime: nodejs12

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 1

handlers:
  - url: /static
    static_dir: build/static
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
